const images = {
	brand: {
		conference: {
			ai: {
				icon: null,
				logo: {
					portrait: null,
					landscape: "/public/images/brand/ai-conference/logo/landscape-dark",
				},
			},
		},
		droneSpace: {
			full: {
				black: {
					landscape: "/public/images/brand/drone-space/full/black/landscape.png",
					portrait: "/public/images/brand/drone-space/full/black/portrait.png",
				},
				original: {
					landscape: "/public/images/brand/drone-space/full/original/landscape.png",
					portrait: "/public/images/brand/drone-space/full/original/portrait.png",
				},
				white: {
					landscape: "/public/images/brand/drone-space/full/white/landscape.png",
					portrait: "/public/images/brand/drone-space/full/white/portrait.png",
				},
			},
			icon: {
				black: "/public/images/brand/drone-space/icon/black.png",
				original: "/public/images/brand/drone-space/icon/original.png",
				white: "/public/images/brand/drone-space/icon/white.png",
			},
			logo: {
				black: {
					landscape: "/public/images/brand/drone-space/logo/black/landscape.png",
					portrait: "/public/images/brand/drone-space/logo/black/portrait.png",
				},
				original: {
					landscape: "/public/images/brand/drone-space/logo/original/landscape.png",
					portrait: "/public/images/brand/drone-space/logo/original/portrait.png",
				},
				white: {
					landscape: "/public/images/brand/drone-space/logo/white/landscape.png",
					portrait: "/public/images/brand/drone-space/logo/white/portrait.png",
				},
			},
		},
	},

	companies: {
		dotsavvy: "/public/images/companies/logo-1.webp",
		must: "/public/images/companies/logo-2.webp",
		hiil: "/public/images/companies/logo-3.webp",
		everseTech: "/public/images/companies/logo-4.webp",
		pathawaysTech: "/public/images/companies/logo-5.webp",
		payd: "/public/images/companies/logo-6.jpeg",
		geoid: "/public/images/companies/logo-7.webp",
		matogen: "/public/images/companies/logo-8.png",
		topCoder: "/public/images/companies/logo-9.svg",
		aiStartup: "/public/images/companies/logo-10.jpg",
		statsspeak: "/public/images/companies/logo-11.jpg",
		kendrone: "/public/images/companies/logo-12.png",
		techMindsetAfrica: "/public/images/companies/logo-13.webp",
		microsoft: "/public/images/companies/logo-14.png",
		mpesaAfrica: "/public/images/companies/logo-15.webp",
		kpmg: "/public/images/companies/logo-16.png",
		droneSpace: "/public/images/companies/logo-17.png",
		safaricom: "/public/images/companies/logo-18.webp",
		quikkApi: "/public/images/companies/logo-20.webp",
		google: "/public/images/companies/logo-21.png",
		safaricom2: "/public/images/companies/logo-22.png",
		think: "/public/images/companies/logo-23.webp",
		wapiPay: "/public/images/companies/logo-24.png",
		vaal: "/public/images/companies/logo-25.svg",
		koena: "/public/images/companies/logo-26.svg",
		geocart: "/public/images/companies/logo-27.png",
		vamboAi: "/public/images/companies/logo-28.png",
		linkarp: "/public/images/companies/logo-29.webp",
		blackRhino: "/public/images/companies/logo-30.svg",
		fahariAviation: "/public/images/companies/logo-31.jfif",
	},

	errors: {
		err404: "/public/images/error/404.svg",
	},

	gallery: {
		conference: {
			yr2022: {
				image1: "/images/gallery/conference/yr2022/image-1.webp",
				image2: "/images/gallery/conference/yr2022/image-2.webp",
				image3: "/images/gallery/conference/yr2022/image-3.webp",
				image4: "/images/gallery/conference/yr2022/image-4.webp",
				image5: "/images/gallery/conference/yr2022/image-5.webp",
			},
			yr2024: {
				image1: "/images/gallery/conference/yr2024/conference-1.webp",
				image2: "/images/gallery/conference/yr2024/conference-2.webp",
				image3: "/images/gallery/conference/yr2024/conference-3.webp",
				image4: "/images/gallery/conference/yr2024/conference-4.webp",
				image5: "/images/gallery/conference/yr2024/conference-5.webp",
				image6: "/images/gallery/conference/yr2024/conference-6.webp",
				image7: "/images/gallery/conference/yr2024/conference-7.webp",
				image8: "/images/gallery/conference/yr2024/conference-8.webp",
				image9: "/images/gallery/conference/yr2024/conference-9.webp",
				image10: "/images/gallery/conference/yr2024/conference-10.webp",
				image11: "/images/gallery/conference/yr2024/conference-11.webp",
				image12: "/images/gallery/conference/yr2024/conference-12.webp",
				image13: "/images/gallery/conference/yr2024/conference-13.webp",
				image14: "/images/gallery/conference/yr2024/conference-14.webp",
				image15: "/images/gallery/conference/yr2024/conference-15.webp",
				image16: "/images/gallery/conference/yr2024/conference-16.webp",
				image17: "/images/gallery/conference/yr2024/conference-17.webp",
				image18: "/images/gallery/conference/yr2024/conference-18.webp",
				image19: "/images/gallery/conference/yr2024/conference-19.webp",
				image20: "/images/gallery/conference/yr2024/conference-20.webp",
				image21: "/images/gallery/conference/yr2024/conference-21.webp",
				image22: "/images/gallery/conference/yr2024/conference-22.webp",
				image23: "/images/gallery/conference/yr2024/conference-23.webp",
				image24: "/images/gallery/conference/yr2024/conference-24.webp",
				image25: "/images/gallery/conference/yr2024/conference-25.webp",
				image26: "/images/gallery/conference/yr2024/conference-26.webp",
				image27: "/images/gallery/conference/yr2024/conference-27.webp",
				image28: "/images/gallery/conference/yr2024/conference-28.webp",
				image29: "/images/gallery/conference/yr2024/conference-29.webp",
				image30: "/images/gallery/conference/yr2024/conference-30.webp",
				image31: "/images/gallery/conference/yr2024/conference-31.webp",
				image32: "/images/gallery/conference/yr2024/conference-32.webp",
				image33: "/images/gallery/conference/yr2024/conference-33.webp",
				image34: "/images/gallery/conference/yr2024/conference-34.webp",
				image35: "/images/gallery/conference/yr2024/conference-35.webp",
				image36: "/images/gallery/conference/yr2024/conference-36.webp",
				image37: "/images/gallery/conference/yr2024/conference-37.webp",
				image38: "/images/gallery/conference/yr2024/conference-38.webp",
				image39: "/images/gallery/conference/yr2024/conference-39.webp",
				image40: "/images/gallery/conference/yr2024/conference-40.webp",
				image41: "/images/gallery/conference/yr2024/conference-41.webp",
				image42: "/images/gallery/conference/yr2024/conference-42.webp",
				image43: "/images/gallery/conference/yr2024/conference-43.webp",
				image44: "/images/gallery/conference/yr2024/conference-44.webp",
				image45: "/images/gallery/conference/yr2024/conference-45.webp",
				image46: "/images/gallery/conference/yr2024/conference-46.webp",
				image47: "/images/gallery/conference/yr2024/conference-47.webp",
				image48: "/images/gallery/conference/yr2024/conference-48.webp",
				image49: "/images/gallery/conference/yr2024/conference-49.webp",
				image50: "/images/gallery/conference/yr2024/conference-50.webp",
				image51: "/images/gallery/conference/yr2024/conference-51.webp",
				image52: "/images/gallery/conference/yr2024/conference-52.webp",
				image53: "/images/gallery/conference/yr2024/conference-53.webp",
				image54: "/images/gallery/conference/yr2024/conference-54.webp",
				image55: "/images/gallery/conference/yr2024/conference-55.webp",
				image56: "/images/gallery/conference/yr2024/conference-56.webp",
				image57: "/images/gallery/conference/yr2024/conference-57.webp",
				image58: "/images/gallery/conference/yr2024/conference-58.webp",
				image59: "/images/gallery/conference/yr2024/conference-59.webp",
				image60: "/images/gallery/conference/yr2024/conference-60.webp",
				image61: "/images/gallery/conference/yr2024/conference-61.webp",
				image62: "/images/gallery/conference/yr2024/conference-62.webp",
				image63: "/images/gallery/conference/yr2024/conference-63.webp",
				image64: "/images/gallery/conference/yr2024/conference-64.webp",
				image65: "/images/gallery/conference/yr2024/conference-65.webp",
				image66: "/images/gallery/conference/yr2024/conference-66.webp",
				image67: "/images/gallery/conference/yr2024/conference-67.webp",
				image68: "/images/gallery/conference/yr2024/conference-68.webp",
				image69: "/images/gallery/conference/yr2024/conference-69.webp",
				image70: "/images/gallery/conference/yr2024/conference-70.webp",
				image71: "/images/gallery/conference/yr2024/conference-71.webp",
				image72: "/images/gallery/conference/yr2024/conference-72.webp",
				image73: "/images/gallery/conference/yr2024/conference-73.webp",
				image74: "/images/gallery/conference/yr2024/conference-74.webp",
				image75: "/images/gallery/conference/yr2024/conference-75.webp",
				image76: "/images/gallery/conference/yr2024/conference-76.webp",
				image77: "/images/gallery/conference/yr2024/conference-77.webp",
				image78: "/images/gallery/conference/yr2024/conference-78.webp",
				image79: "/images/gallery/conference/yr2024/conference-79.webp",
				image80: "/images/gallery/conference/yr2024/conference-80.webp",
				image81: "/images/gallery/conference/yr2024/conference-81.webp",
				image82: "/images/gallery/conference/yr2024/conference-82.webp",
				image83: "/images/gallery/conference/yr2024/conference-83.webp",
				image84: "/images/gallery/conference/yr2024/conference-84.webp",
				image85: "/images/gallery/conference/yr2024/conference-85.webp",
				image86: "/images/gallery/conference/yr2024/conference-86.webp",
				image87: "/images/gallery/conference/yr2024/conference-87.webp",
				image88: "/images/gallery/conference/yr2024/conference-88.webp",
				image89: "/images/gallery/conference/yr2024/conference-89.webp",
				image90: "/images/gallery/conference/yr2024/conference-90.webp",
				image91: "/images/gallery/conference/yr2024/conference-91.webp",
				image92: "/images/gallery/conference/yr2024/conference-92.webp",
				image93: "/images/gallery/conference/yr2024/conference-93.webp",
				image94: "/images/gallery/conference/yr2024/conference-94.webp",
				image95: "/images/gallery/conference/yr2024/conference-95.webp",
				image96: "/images/gallery/conference/yr2024/conference-96.webp",
				image97: "/images/gallery/conference/yr2024/conference-97.webp",
				image98: "/images/gallery/conference/yr2024/conference-98.webp",
				image99: "/images/gallery/conference/yr2024/conference-99.webp",
				image100: "/images/gallery/conference/yr2024/conference-100.webp",
				image101: "/images/gallery/conference/yr2024/conference-101.webp",
				image102: "/images/gallery/conference/yr2024/conference-102.webp",
				image103: "/images/gallery/conference/yr2024/conference-103.webp",
				image104: "/images/gallery/conference/yr2024/conference-104.webp",
				image105: "/images/gallery/conference/yr2024/conference-105.webp",
				image106: "/images/gallery/conference/yr2024/conference-106.webp",
				image107: "/images/gallery/conference/yr2024/conference-107.webp",
				image108: "/images/gallery/conference/yr2024/conference-108.webp",
				image109: "/images/gallery/conference/yr2024/conference-109.webp",
				image110: "/images/gallery/conference/yr2024/conference-110.webp",
				image111: "/images/gallery/conference/yr2024/conference-111.webp",
				image112: "/images/gallery/conference/yr2024/conference-112.webp",
				image113: "/images/gallery/conference/yr2024/conference-113.webp",
				image114: "/images/gallery/conference/yr2024/conference-114.webp",
				image115: "/images/gallery/conference/yr2024/conference-115.webp",
				image116: "/images/gallery/conference/yr2024/conference-116.webp",
				image117: "/images/gallery/conference/yr2024/conference-117.webp",
				image118: "/images/gallery/conference/yr2024/conference-118.webp",
				image119: "/images/gallery/conference/yr2024/conference-119.webp",
				image120: "/images/gallery/conference/yr2024/conference-120.webp",
				image121: "/images/gallery/conference/yr2024/conference-121.webp",
				image122: "/images/gallery/conference/yr2024/conference-122.webp",
				image123: "/images/gallery/conference/yr2024/conference-123.webp",
				image124: "/images/gallery/conference/yr2024/conference-124.webp",
				image125: "/images/gallery/conference/yr2024/conference-125.webp",
				image126: "/images/gallery/conference/yr2024/conference-126.webp",
				image127: "/images/gallery/conference/yr2024/conference-127.webp",
				image128: "/images/gallery/conference/yr2024/conference-128.webp",
				image129: "/images/gallery/conference/yr2024/conference-129.webp",
				image130: "/images/gallery/conference/yr2024/conference-130.webp",
				image131: "/images/gallery/conference/yr2024/conference-131.webp",
				image132: "/images/gallery/conference/yr2024/conference-132.webp",
				image133: "/images/gallery/conference/yr2024/conference-133.webp",
				image134: "/images/gallery/conference/yr2024/conference-134.webp",
				image135: "/images/gallery/conference/yr2024/conference-135.webp",
				image136: "/images/gallery/conference/yr2024/conference-136.webp",
				image137: "/images/gallery/conference/yr2024/conference-137.webp",
				image138: "/images/gallery/conference/yr2024/conference-138.webp",
				image139: "/images/gallery/conference/yr2024/conference-139.webp",
				image140: "/images/gallery/conference/yr2024/conference-140.webp",
				image141: "/images/gallery/conference/yr2024/conference-141.webp",
				image142: "/images/gallery/conference/yr2024/conference-142.webp",
				image143: "/images/gallery/conference/yr2024/conference-143.webp",
				image144: "/images/gallery/conference/yr2024/conference-144.webp",
			},
		},

		expo: {
			yr2022: {
				image1: "/images/gallery/expo/yr2022/image-1.webp",
				image2: "/images/gallery/expo/yr2022/image-2.webp",
				image3: "/images/gallery/expo/yr2022/image-3.webp",
				image4: "/images/gallery/expo/yr2022/image-4.webp",
				image5: "/images/gallery/expo/yr2022/image-5.webp",
				image6: "/images/gallery/expo/yr2022/image-6.webp",
				image7: "/images/gallery/expo/yr2022/image-7.webp",
				image8: "/images/gallery/expo/yr2022/image-8.webp",
				image9: "/images/gallery/expo/yr2022/image-9.webp",
				image10: "/images/gallery/expo/yr2022/image-10.webp",
				image11: "/images/gallery/expo/yr2022/image-11.webp",
				image12: "/images/gallery/expo/yr2022/image-12.webp",
				image13: "/images/gallery/expo/yr2022/image-13.webp",
				image14: "/images/gallery/expo/yr2022/image-14.webp",
				image15: "/images/gallery/expo/yr2022/image-15.webp",
			},
			yr2024: {
				image1: "/images/gallery/expo/yr2024/expo-1.webp",
				image2: "/images/gallery/expo/yr2024/expo-2.webp",
				image3: "/images/gallery/expo/yr2024/expo-3.webp",
				image4: "/images/gallery/expo/yr2024/expo-4.webp",
				image5: "/images/gallery/expo/yr2024/expo-5.webp",
				image6: "/images/gallery/expo/yr2024/expo-6.webp",
				image7: "/images/gallery/expo/yr2024/expo-7.webp",
				image8: "/images/gallery/expo/yr2024/expo-8.webp",
				image9: "/images/gallery/expo/yr2024/expo-9.webp",
				image10: "/images/gallery/expo/yr2024/expo-10.webp",
				image11: "/images/gallery/expo/yr2024/expo-11.webp",
				image12: "/images/gallery/expo/yr2024/expo-12.webp",
				image13: "/images/gallery/expo/yr2024/expo-13.webp",
				image14: "/images/gallery/expo/yr2024/expo-14.webp",
				image15: "/images/gallery/expo/yr2024/expo-15.webp",
				image16: "/images/gallery/expo/yr2024/expo-16.webp",
				image17: "/images/gallery/expo/yr2024/expo-17.webp",
				image18: "/images/gallery/expo/yr2024/expo-18.webp",
				image19: "/images/gallery/expo/yr2024/expo-19.webp",
				image20: "/images/gallery/expo/yr2024/expo-20.webp",
				image21: "/images/gallery/expo/yr2024/expo-21.webp",
				image22: "/images/gallery/expo/yr2024/expo-22.webp",
				image23: "/images/gallery/expo/yr2024/expo-23.webp",
				image24: "/images/gallery/expo/yr2024/expo-24.webp",
				image25: "/images/gallery/expo/yr2024/expo-25.webp",
				image26: "/images/gallery/expo/yr2024/expo-26.webp",
				image27: "/images/gallery/expo/yr2024/expo-27.webp",
				image28: "/images/gallery/expo/yr2024/expo-28.webp",
				image29: "/images/gallery/expo/yr2024/expo-29.webp",
				image30: "/images/gallery/expo/yr2024/expo-30.webp",
				image31: "/images/gallery/expo/yr2024/expo-31.webp",
				image32: "/images/gallery/expo/yr2024/expo-32.webp",
				image33: "/images/gallery/expo/yr2024/expo-33.webp",
				image34: "/images/gallery/expo/yr2024/expo-34.webp",
				image35: "/images/gallery/expo/yr2024/expo-35.webp",
				image36: "/images/gallery/expo/yr2024/expo-36.webp",
			},
		},

		hackathon: {
			yr2024: {
				image1: "/images/gallery/hackathon/yr2024/hackathon-1.webp",
				image2: "/images/gallery/hackathon/yr2024/hackathon-2.webp",
				image3: "/images/gallery/hackathon/yr2024/hackathon-3.webp",
				image4: "/images/gallery/hackathon/yr2024/hackathon-4.webp",
				image5: "/images/gallery/hackathon/yr2024/hackathon-5.webp",
				image6: "/images/gallery/hackathon/yr2024/hackathon-6.webp",
				image7: "/images/gallery/hackathon/yr2024/hackathon-7.webp",
				image8: "/images/gallery/hackathon/yr2024/hackathon-8.webp",
				image9: "/images/gallery/hackathon/yr2024/hackathon-9.webp",
			},
		},
	},

	partners: {
		media: {
			image1: "/public/images/partners/media/media-1.webp",
			image2: "/public/images/partners/media/media-2.webp",
			image3: "/public/images/partners/media/media-3.webp",
			image4: "/public/images/partners/media/media-4.webp",
			image5: "/public/images/partners/media/media-5.webp",
			image6: "/public/images/partners/media/media-6.png",
			image7: "/public/images/partners/media/media-7.png",
			image8: "/public/images/partners/media/media-8.jpg",
			image9: "/public/images/partners/media/media-9.png",
			image10: "/public/images/partners/media/media-10.webp",
			image11: "/public/images/partners/media/media-11.webp",
			image12: "/public/images/partners/media/media-12.webp",
			image13: "/public/images/partners/media/media-13.webp",
			image14: "/public/images/partners/media/media-14.webp",
		},
	},

	people: {
		michaelZimba: "/public/images/people/speaker-1.webp",
		michaelMichie: "/public/images/people/speaker-2.webp",
		joelOnditi: "/public/images/people/speaker-3.webp",
		benaiahWepundi: "/public/images/people/speaker-4.webp",
		solomonWanjiru: "/public/images/people/speaker-5.webp",
		violetOchieng: "/public/images/people/speaker-6.webp",
		lyelaMutisya: "/public/images/people/speaker-7.webp",
		nathanRoss: "/public/images/people/speaker-8.webp",
		mwangiKirubi: "/public/images/people/speaker-9.webp",
		sahilPatel: "/public/images/people/speaker-10.webp",
		robinsonMuiru: "/public/images/people/speaker-11.webp",
		brightGameli: "/public/images/people/speaker-12.webp",
		koyundiBryan: "/public/images/people/speaker-13.webp",
		tawandaChihambakwe: "/public/images/people/speaker-14.webp",
		tolgaOrs: "/public/images/people/speaker-15.webp",
		robertBlair: "/public/images/people/speaker-16.webp",
		denisMutua: "/public/images/people/speaker-17.webp",
		pamelaAdede: "/public/images/people/speaker-18.webp",
		washingtonOgol: "/public/images/people/speaker-19.webp",
		antonyNgatia: "/public/images/people/speaker-20.webp",
		craigCleave: "/public/images/people/speaker-21.webp",
		joanMbesya: "/public/images/people/speaker-22.webp",
		bethanyJepchumba: "/public/images/people/speaker-23.webp",
		dennisMwighusa: "/public/images/people/speaker-24.webp",
		winnieNjeri: "/public/images/people/speaker-25.jpeg",
		ezekielOnyango: "/public/images/people/speaker-26.webp",
		brianGeorge: "/public/images/people/speaker-27.webp",
		mercyMakau: "/public/images/people/speaker-28.webp",
		jasonMasai: "/public/images/people/speaker-29.webp",
		sandeepMain: "/public/images/people/speaker-30.webp",
		eddieNdichu: "/public/images/people/speaker-31.webp",
		douglasOkwemba: "/public/images/people/speaker-32.webp",
		toshGitonga: "/public/images/people/speaker-33.webp",
		priscahKinyanjui: "/public/images/people/speaker-34.webp",
		brianOmwenga: "/public/images/people/speaker-35.webp",
		chepkemoiMagdaline: "/public/images/people/speaker-36.webp",
		emmanAtwa: "/public/images/people/speaker-37.webp",
		mercyMau: "/public/images/people/speaker-38.webp",
		hawkinsMusili: "/public/images/people/speaker-39.webp",
		deanGichukie: "/public/images/people/speaker-40.webp",
		martinMirero: "/public/images/people/speaker-41.webp",
		ednaKarijo: "/public/images/people/speaker-42.webp",
		charlesMurito: "/public/images/people/speaker-43.webp",
		kamauMaina: "/public/images/people/speaker-44.webp",
		sharonHoli: "/public/images/people/speaker-45.webp",
		georgeMatuthu: "/public/images/people/speaker-46.webp",
		loiseMwangi: "/public/images/people/speaker-47.webp",
		alfredOngere: "/public/images/people/speaker-48.webp",
		hillaryWangila: "/public/images/people/speaker-49.webp",
		francisOmondi: "/public/images/people/speaker-50.webp",
		mosesKimebaro: "/public/images/people/speaker-51.webp",
		georgeOgada: "/public/images/people/speaker-52.webp",
		labanCliff: "/public/images/people/speaker-53.webp",
	},

	posters: {
		speakers: {
			joanMbesya: "/public/images/posters/speakers/poster-1.webp",
			washingtonOgol: "/public/images/posters/speakers/poster-2.webp",
			tawandaChihambakwe: "/public/images/posters/speakers/poster-3.webp",
			eddieNdichu: "/public/images/posters/speakers/poster-4.webp",
		},

		poster1: "/public/images/posters/poster-1.webp",
		poster2: "/public/images/posters/poster-2.webp",
		poster3: "/public/images/posters/poster-3.webp",
		poster4: "/public/images/posters/poster-4.jpeg",
	},
};

export default images;

// remember to remove public from path
