import { HOSTED_BASE_URL } from '@/data/constants';

const icons8 = `https://img.icons8.com`;
const baseUrl = {
  droneSpace: `${HOSTED_BASE_URL.DRONE_SPACE}/images`,
  conference: `${HOSTED_BASE_URL.CONFERENCE}/images`,
};

export const images = {
  icons: {
    social: {
      facebook: `${icons8}/?size=100&id=13912&format=png&color=000000`,
      instagram: `${icons8}/?size=100&id=32323&format=png&color=000000`,
      twitterx: `${icons8}/?size=100&id=ClbD5JTFM7FA&format=png&color=000000`,
      linkedin: `${icons8}/?size=100&id=13930&format=png&color=000000`,
      whatsapp: `${icons8}/?size=100&id=16713&format=png&color=000000`,
    },

    google: `${icons8}/?size=100&id=17949&format=png&color=000000`,
    credentials: `${icons8}/?size=100&id=jicLxt1sA2qa&format=png&color=000000`,
  },

  brand: {
    conference: {
      icon: {
        dark: `${baseUrl.conference}/brand/icon/dark.png`,
        light: `${baseUrl.conference}/brand/icon/light.png`,
      },
      logo: {
        landscape: {
          dark: `${baseUrl.conference}/brand/logo/landscape/dark.png`,
          light: `${baseUrl.conference}/brand/logo/landscape/light.png`,
        },
        potrait: {
          dark: `${baseUrl.conference}/brand/logo/potrait/dark.png`,
          light: `${baseUrl.conference}/brand/logo/potrait/light.png`,
        },
      },
    },

    droneSpace: {
      icon: {
        black: `${baseUrl.droneSpace}/brand/icon/black.png`,
        default: `${baseUrl.droneSpace}/brand/icon/default.png`,
        white: `${baseUrl.droneSpace}/brand/icon/white.png`,
      },
      logo: {
        landscape: {
          black: `${baseUrl.droneSpace}/brand/logo/landscape/black.png`,
          default: `${baseUrl.droneSpace}/brand/logo/landscape/default.png`,
          white: `${baseUrl.droneSpace}/brand/logo/landscape/white.png`,
        },
        potrait: {
          black: `${baseUrl.droneSpace}/brand/logo/potrait/black.png`,
          default: `${baseUrl.droneSpace}/brand/logo/potrait/default.png`,
          white: `${baseUrl.droneSpace}/brand/logo/potrait/white.png`,
        },
      },
    },
  },

  companies: {
    dotsavvy: `${baseUrl.conference}/companies/logo-1.webp`,
    must: `${baseUrl.conference}/companies/logo-2.webp`,
    hiil: `${baseUrl.conference}/companies/logo-3.webp`,
    everseTech: `${baseUrl.conference}/companies/logo-4.webp`,
    pathawaysTech: `${baseUrl.conference}/companies/logo-5.webp`,
    payd: `${baseUrl.conference}/companies/logo-6.jpeg`,
    geoid: `${baseUrl.conference}/companies/logo-7.webp`,
    matogen: `${baseUrl.conference}/companies/logo-8.png`,
    topCoder: `${baseUrl.conference}/companies/logo-9.svg`,
    aiStartup: `${baseUrl.conference}/companies/logo-10.jpg`,
    statsspeak: `${baseUrl.conference}/companies/logo-11.jpg`,
    kendrone: `${baseUrl.conference}/companies/logo-12.png`,
    techMindsetAfrica: `${baseUrl.conference}/companies/logo-13.webp`,
    microsoft: `${baseUrl.conference}/companies/logo-14.png`,
    mpesaAfrica: `${baseUrl.conference}/companies/logo-15.webp`,
    kpmg: `${baseUrl.conference}/companies/logo-16.png`,
    droneSpace: `${baseUrl.conference}/companies/logo-17.png`,
    safaricom: `${baseUrl.conference}/companies/logo-18.webp`,
    quikkApi: `${baseUrl.conference}/companies/logo-20.webp`,
    google: `${baseUrl.conference}/companies/logo-21.png`,
    safaricom2: `${baseUrl.conference}/companies/logo-22.png`,
    think: `${baseUrl.conference}/companies/logo-23.webp`,
    wapiPay: `${baseUrl.conference}/companies/logo-24.png`,
    vaal: `${baseUrl.conference}/companies/logo-25.svg`,
    koena: `${baseUrl.conference}/companies/logo-26.svg`,
    geocart: `${baseUrl.conference}/companies/logo-27.png`,
    vamboAi: `${baseUrl.conference}/companies/logo-28.png`,
    linkarp: `${baseUrl.conference}/companies/logo-29.webp`,
    blackRhino: `${baseUrl.conference}/companies/logo-30.svg`,
    fahariAviation: `${baseUrl.conference}/companies/logo-31.jfif`,
  },

  gallery: {
    conference: {
      yr2022: {
        image1: `${baseUrl.conference}/gallery/conference/yr2022/image-1.webp`,
        image2: `${baseUrl.conference}/gallery/conference/yr2022/image-2.webp`,
        image3: `${baseUrl.conference}/gallery/conference/yr2022/image-3.webp`,
        image4: `${baseUrl.conference}/gallery/conference/yr2022/image-4.webp`,
        image5: `${baseUrl.conference}/gallery/conference/yr2022/image-5.webp`,
      },
      yr2024: {
        image1: `${baseUrl.conference}/gallery/conference/yr2024/conference-1.webp`,
        image2: `${baseUrl.conference}/gallery/conference/yr2024/conference-2.webp`,
        image3: `${baseUrl.conference}/gallery/conference/yr2024/conference-3.webp`,
        image4: `${baseUrl.conference}/gallery/conference/yr2024/conference-4.webp`,
        image5: `${baseUrl.conference}/gallery/conference/yr2024/conference-5.webp`,
        image6: `${baseUrl.conference}/gallery/conference/yr2024/conference-6.webp`,
        image7: `${baseUrl.conference}/gallery/conference/yr2024/conference-7.webp`,
        image8: `${baseUrl.conference}/gallery/conference/yr2024/conference-8.webp`,
        image9: `${baseUrl.conference}/gallery/conference/yr2024/conference-9.webp`,
        image10: `${baseUrl.conference}/gallery/conference/yr2024/conference-10.webp`,
        image11: `${baseUrl.conference}/gallery/conference/yr2024/conference-11.webp`,
        image12: `${baseUrl.conference}/gallery/conference/yr2024/conference-12.webp`,
        image13: `${baseUrl.conference}/gallery/conference/yr2024/conference-13.webp`,
        image14: `${baseUrl.conference}/gallery/conference/yr2024/conference-14.webp`,
        image15: `${baseUrl.conference}/gallery/conference/yr2024/conference-15.webp`,
        image16: `${baseUrl.conference}/gallery/conference/yr2024/conference-16.webp`,
        image17: `${baseUrl.conference}/gallery/conference/yr2024/conference-17.webp`,
        image18: `${baseUrl.conference}/gallery/conference/yr2024/conference-18.webp`,
        image19: `${baseUrl.conference}/gallery/conference/yr2024/conference-19.webp`,
        image20: `${baseUrl.conference}/gallery/conference/yr2024/conference-20.webp`,
        image21: `${baseUrl.conference}/gallery/conference/yr2024/conference-21.webp`,
        image22: `${baseUrl.conference}/gallery/conference/yr2024/conference-22.webp`,
        image23: `${baseUrl.conference}/gallery/conference/yr2024/conference-23.webp`,
        image24: `${baseUrl.conference}/gallery/conference/yr2024/conference-24.webp`,
        image25: `${baseUrl.conference}/gallery/conference/yr2024/conference-25.webp`,
        image26: `${baseUrl.conference}/gallery/conference/yr2024/conference-26.webp`,
        image27: `${baseUrl.conference}/gallery/conference/yr2024/conference-27.webp`,
        image28: `${baseUrl.conference}/gallery/conference/yr2024/conference-28.webp`,
        image29: `${baseUrl.conference}/gallery/conference/yr2024/conference-29.webp`,
        image30: `${baseUrl.conference}/gallery/conference/yr2024/conference-30.webp`,
        image31: `${baseUrl.conference}/gallery/conference/yr2024/conference-31.webp`,
        image32: `${baseUrl.conference}/gallery/conference/yr2024/conference-32.webp`,
        image33: `${baseUrl.conference}/gallery/conference/yr2024/conference-33.webp`,
        image34: `${baseUrl.conference}/gallery/conference/yr2024/conference-34.webp`,
        image35: `${baseUrl.conference}/gallery/conference/yr2024/conference-35.webp`,
        image36: `${baseUrl.conference}/gallery/conference/yr2024/conference-36.webp`,
        image37: `${baseUrl.conference}/gallery/conference/yr2024/conference-37.webp`,
        image38: `${baseUrl.conference}/gallery/conference/yr2024/conference-38.webp`,
        image39: `${baseUrl.conference}/gallery/conference/yr2024/conference-39.webp`,
        image40: `${baseUrl.conference}/gallery/conference/yr2024/conference-40.webp`,
        image41: `${baseUrl.conference}/gallery/conference/yr2024/conference-41.webp`,
        image42: `${baseUrl.conference}/gallery/conference/yr2024/conference-42.webp`,
        image43: `${baseUrl.conference}/gallery/conference/yr2024/conference-43.webp`,
        image44: `${baseUrl.conference}/gallery/conference/yr2024/conference-44.webp`,
        image45: `${baseUrl.conference}/gallery/conference/yr2024/conference-45.webp`,
        image46: `${baseUrl.conference}/gallery/conference/yr2024/conference-46.webp`,
        image47: `${baseUrl.conference}/gallery/conference/yr2024/conference-47.webp`,
        image48: `${baseUrl.conference}/gallery/conference/yr2024/conference-48.webp`,
        image49: `${baseUrl.conference}/gallery/conference/yr2024/conference-49.webp`,
        image50: `${baseUrl.conference}/gallery/conference/yr2024/conference-50.webp`,
        image51: `${baseUrl.conference}/gallery/conference/yr2024/conference-51.webp`,
        image52: `${baseUrl.conference}/gallery/conference/yr2024/conference-52.webp`,
        image53: `${baseUrl.conference}/gallery/conference/yr2024/conference-53.webp`,
        image54: `${baseUrl.conference}/gallery/conference/yr2024/conference-54.webp`,
        image55: `${baseUrl.conference}/gallery/conference/yr2024/conference-55.webp`,
        image56: `${baseUrl.conference}/gallery/conference/yr2024/conference-56.webp`,
        image57: `${baseUrl.conference}/gallery/conference/yr2024/conference-57.webp`,
        image58: `${baseUrl.conference}/gallery/conference/yr2024/conference-58.webp`,
        image59: `${baseUrl.conference}/gallery/conference/yr2024/conference-59.webp`,
        image60: `${baseUrl.conference}/gallery/conference/yr2024/conference-60.webp`,
        image61: `${baseUrl.conference}/gallery/conference/yr2024/conference-61.webp`,
        image62: `${baseUrl.conference}/gallery/conference/yr2024/conference-62.webp`,
        image63: `${baseUrl.conference}/gallery/conference/yr2024/conference-63.webp`,
        image64: `${baseUrl.conference}/gallery/conference/yr2024/conference-64.webp`,
        image65: `${baseUrl.conference}/gallery/conference/yr2024/conference-65.webp`,
        image66: `${baseUrl.conference}/gallery/conference/yr2024/conference-66.webp`,
        image67: `${baseUrl.conference}/gallery/conference/yr2024/conference-67.webp`,
        image68: `${baseUrl.conference}/gallery/conference/yr2024/conference-68.webp`,
        image69: `${baseUrl.conference}/gallery/conference/yr2024/conference-69.webp`,
        image70: `${baseUrl.conference}/gallery/conference/yr2024/conference-70.webp`,
        image71: `${baseUrl.conference}/gallery/conference/yr2024/conference-71.webp`,
        image72: `${baseUrl.conference}/gallery/conference/yr2024/conference-72.webp`,
        image73: `${baseUrl.conference}/gallery/conference/yr2024/conference-73.webp`,
        image74: `${baseUrl.conference}/gallery/conference/yr2024/conference-74.webp`,
        image75: `${baseUrl.conference}/gallery/conference/yr2024/conference-75.webp`,
        image76: `${baseUrl.conference}/gallery/conference/yr2024/conference-76.webp`,
        image77: `${baseUrl.conference}/gallery/conference/yr2024/conference-77.webp`,
        image78: `${baseUrl.conference}/gallery/conference/yr2024/conference-78.webp`,
        image79: `${baseUrl.conference}/gallery/conference/yr2024/conference-79.webp`,
        image80: `${baseUrl.conference}/gallery/conference/yr2024/conference-80.webp`,
        image81: `${baseUrl.conference}/gallery/conference/yr2024/conference-81.webp`,
        image82: `${baseUrl.conference}/gallery/conference/yr2024/conference-82.webp`,
        image83: `${baseUrl.conference}/gallery/conference/yr2024/conference-83.webp`,
        image84: `${baseUrl.conference}/gallery/conference/yr2024/conference-84.webp`,
        image85: `${baseUrl.conference}/gallery/conference/yr2024/conference-85.webp`,
        image86: `${baseUrl.conference}/gallery/conference/yr2024/conference-86.webp`,
        image87: `${baseUrl.conference}/gallery/conference/yr2024/conference-87.webp`,
        image88: `${baseUrl.conference}/gallery/conference/yr2024/conference-88.webp`,
        image89: `${baseUrl.conference}/gallery/conference/yr2024/conference-89.webp`,
        image90: `${baseUrl.conference}/gallery/conference/yr2024/conference-90.webp`,
        image91: `${baseUrl.conference}/gallery/conference/yr2024/conference-91.webp`,
        image92: `${baseUrl.conference}/gallery/conference/yr2024/conference-92.webp`,
        image93: `${baseUrl.conference}/gallery/conference/yr2024/conference-93.webp`,
        image94: `${baseUrl.conference}/gallery/conference/yr2024/conference-94.webp`,
        image95: `${baseUrl.conference}/gallery/conference/yr2024/conference-95.webp`,
        image96: `${baseUrl.conference}/gallery/conference/yr2024/conference-96.webp`,
        image97: `${baseUrl.conference}/gallery/conference/yr2024/conference-97.webp`,
        image98: `${baseUrl.conference}/gallery/conference/yr2024/conference-98.webp`,
        image99: `${baseUrl.conference}/gallery/conference/yr2024/conference-99.webp`,
        image100: `${baseUrl.conference}/gallery/conference/yr2024/conference-100.webp`,
        image101: `${baseUrl.conference}/gallery/conference/yr2024/conference-101.webp`,
        image102: `${baseUrl.conference}/gallery/conference/yr2024/conference-102.webp`,
        image103: `${baseUrl.conference}/gallery/conference/yr2024/conference-103.webp`,
        image104: `${baseUrl.conference}/gallery/conference/yr2024/conference-104.webp`,
        image105: `${baseUrl.conference}/gallery/conference/yr2024/conference-105.webp`,
        image106: `${baseUrl.conference}/gallery/conference/yr2024/conference-106.webp`,
        image107: `${baseUrl.conference}/gallery/conference/yr2024/conference-107.webp`,
        image108: `${baseUrl.conference}/gallery/conference/yr2024/conference-108.webp`,
        image109: `${baseUrl.conference}/gallery/conference/yr2024/conference-109.webp`,
        image110: `${baseUrl.conference}/gallery/conference/yr2024/conference-110.webp`,
        image111: `${baseUrl.conference}/gallery/conference/yr2024/conference-111.webp`,
        image112: `${baseUrl.conference}/gallery/conference/yr2024/conference-112.webp`,
        image113: `${baseUrl.conference}/gallery/conference/yr2024/conference-113.webp`,
        image114: `${baseUrl.conference}/gallery/conference/yr2024/conference-114.webp`,
        image115: `${baseUrl.conference}/gallery/conference/yr2024/conference-115.webp`,
        image116: `${baseUrl.conference}/gallery/conference/yr2024/conference-116.webp`,
        image117: `${baseUrl.conference}/gallery/conference/yr2024/conference-117.webp`,
        image118: `${baseUrl.conference}/gallery/conference/yr2024/conference-118.webp`,
        image119: `${baseUrl.conference}/gallery/conference/yr2024/conference-119.webp`,
        image120: `${baseUrl.conference}/gallery/conference/yr2024/conference-120.webp`,
        image121: `${baseUrl.conference}/gallery/conference/yr2024/conference-121.webp`,
        image122: `${baseUrl.conference}/gallery/conference/yr2024/conference-122.webp`,
        image123: `${baseUrl.conference}/gallery/conference/yr2024/conference-123.webp`,
        image124: `${baseUrl.conference}/gallery/conference/yr2024/conference-124.webp`,
        image125: `${baseUrl.conference}/gallery/conference/yr2024/conference-125.webp`,
        image126: `${baseUrl.conference}/gallery/conference/yr2024/conference-126.webp`,
        image127: `${baseUrl.conference}/gallery/conference/yr2024/conference-127.webp`,
        image128: `${baseUrl.conference}/gallery/conference/yr2024/conference-128.webp`,
        image129: `${baseUrl.conference}/gallery/conference/yr2024/conference-129.webp`,
        image130: `${baseUrl.conference}/gallery/conference/yr2024/conference-130.webp`,
        image131: `${baseUrl.conference}/gallery/conference/yr2024/conference-131.webp`,
        image132: `${baseUrl.conference}/gallery/conference/yr2024/conference-132.webp`,
        image133: `${baseUrl.conference}/gallery/conference/yr2024/conference-133.webp`,
        image134: `${baseUrl.conference}/gallery/conference/yr2024/conference-134.webp`,
        image135: `${baseUrl.conference}/gallery/conference/yr2024/conference-135.webp`,
        image136: `${baseUrl.conference}/gallery/conference/yr2024/conference-136.webp`,
        image137: `${baseUrl.conference}/gallery/conference/yr2024/conference-137.webp`,
        image138: `${baseUrl.conference}/gallery/conference/yr2024/conference-138.webp`,
        image139: `${baseUrl.conference}/gallery/conference/yr2024/conference-139.webp`,
        image140: `${baseUrl.conference}/gallery/conference/yr2024/conference-140.webp`,
        image141: `${baseUrl.conference}/gallery/conference/yr2024/conference-141.webp`,
        image142: `${baseUrl.conference}/gallery/conference/yr2024/conference-142.webp`,
        image143: `${baseUrl.conference}/gallery/conference/yr2024/conference-143.webp`,
        image144: `${baseUrl.conference}/gallery/conference/yr2024/conference-144.webp`,
      },
    },

    expo: {
      yr2022: {
        image1: `${baseUrl.conference}/gallery/expo/yr2022/image-1.webp`,
        image2: `${baseUrl.conference}/gallery/expo/yr2022/image-2.webp`,
        image3: `${baseUrl.conference}/gallery/expo/yr2022/image-3.webp`,
        image4: `${baseUrl.conference}/gallery/expo/yr2022/image-4.webp`,
        image5: `${baseUrl.conference}/gallery/expo/yr2022/image-5.webp`,
        image6: `${baseUrl.conference}/gallery/expo/yr2022/image-6.webp`,
        image7: `${baseUrl.conference}/gallery/expo/yr2022/image-7.webp`,
        image8: `${baseUrl.conference}/gallery/expo/yr2022/image-8.webp`,
        image9: `${baseUrl.conference}/gallery/expo/yr2022/image-9.webp`,
        image10: `${baseUrl.conference}/gallery/expo/yr2022/image-10.webp`,
        image11: `${baseUrl.conference}/gallery/expo/yr2022/image-11.webp`,
        image12: `${baseUrl.conference}/gallery/expo/yr2022/image-12.webp`,
        image13: `${baseUrl.conference}/gallery/expo/yr2022/image-13.webp`,
        image14: `${baseUrl.conference}/gallery/expo/yr2022/image-14.webp`,
        image15: `${baseUrl.conference}/gallery/expo/yr2022/image-15.webp`,
      },
      yr2024: {
        image1: `${baseUrl.conference}/gallery/expo/yr2024/expo-1.webp`,
        image2: `${baseUrl.conference}/gallery/expo/yr2024/expo-2.webp`,
        image3: `${baseUrl.conference}/gallery/expo/yr2024/expo-3.webp`,
        image4: `${baseUrl.conference}/gallery/expo/yr2024/expo-4.webp`,
        image5: `${baseUrl.conference}/gallery/expo/yr2024/expo-5.webp`,
        image6: `${baseUrl.conference}/gallery/expo/yr2024/expo-6.webp`,
        image7: `${baseUrl.conference}/gallery/expo/yr2024/expo-7.webp`,
        image8: `${baseUrl.conference}/gallery/expo/yr2024/expo-8.webp`,
        image9: `${baseUrl.conference}/gallery/expo/yr2024/expo-9.webp`,
        image10: `${baseUrl.conference}/gallery/expo/yr2024/expo-10.webp`,
        image11: `${baseUrl.conference}/gallery/expo/yr2024/expo-11.webp`,
        image12: `${baseUrl.conference}/gallery/expo/yr2024/expo-12.webp`,
        image13: `${baseUrl.conference}/gallery/expo/yr2024/expo-13.webp`,
        image14: `${baseUrl.conference}/gallery/expo/yr2024/expo-14.webp`,
        image15: `${baseUrl.conference}/gallery/expo/yr2024/expo-15.webp`,
        image16: `${baseUrl.conference}/gallery/expo/yr2024/expo-16.webp`,
        image17: `${baseUrl.conference}/gallery/expo/yr2024/expo-17.webp`,
        image18: `${baseUrl.conference}/gallery/expo/yr2024/expo-18.webp`,
        image19: `${baseUrl.conference}/gallery/expo/yr2024/expo-19.webp`,
        image20: `${baseUrl.conference}/gallery/expo/yr2024/expo-20.webp`,
        image21: `${baseUrl.conference}/gallery/expo/yr2024/expo-21.webp`,
        image22: `${baseUrl.conference}/gallery/expo/yr2024/expo-22.webp`,
        image23: `${baseUrl.conference}/gallery/expo/yr2024/expo-23.webp`,
        image24: `${baseUrl.conference}/gallery/expo/yr2024/expo-24.webp`,
        image25: `${baseUrl.conference}/gallery/expo/yr2024/expo-25.webp`,
        image26: `${baseUrl.conference}/gallery/expo/yr2024/expo-26.webp`,
        image27: `${baseUrl.conference}/gallery/expo/yr2024/expo-27.webp`,
        image28: `${baseUrl.conference}/gallery/expo/yr2024/expo-28.webp`,
        image29: `${baseUrl.conference}/gallery/expo/yr2024/expo-29.webp`,
        image30: `${baseUrl.conference}/gallery/expo/yr2024/expo-30.webp`,
        image31: `${baseUrl.conference}/gallery/expo/yr2024/expo-31.webp`,
        image32: `${baseUrl.conference}/gallery/expo/yr2024/expo-32.webp`,
        image33: `${baseUrl.conference}/gallery/expo/yr2024/expo-33.webp`,
        image34: `${baseUrl.conference}/gallery/expo/yr2024/expo-34.webp`,
        image35: `${baseUrl.conference}/gallery/expo/yr2024/expo-35.webp`,
        image36: `${baseUrl.conference}/gallery/expo/yr2024/expo-36.webp`,
      },
    },

    hackathon: {
      yr2024: {
        image1: `${baseUrl.conference}/gallery/hackathon/yr2024/hackathon-1.webp`,
        image2: `${baseUrl.conference}/gallery/hackathon/yr2024/hackathon-2.webp`,
        image3: `${baseUrl.conference}/gallery/hackathon/yr2024/hackathon-3.webp`,
        image4: `${baseUrl.conference}/gallery/hackathon/yr2024/hackathon-4.webp`,
        image5: `${baseUrl.conference}/gallery/hackathon/yr2024/hackathon-5.webp`,
        image6: `${baseUrl.conference}/gallery/hackathon/yr2024/hackathon-6.webp`,
        image7: `${baseUrl.conference}/gallery/hackathon/yr2024/hackathon-7.webp`,
        image8: `${baseUrl.conference}/gallery/hackathon/yr2024/hackathon-8.webp`,
        image9: `${baseUrl.conference}/gallery/hackathon/yr2024/hackathon-9.webp`,
      },
    },
  },

  partners: {
    media: {
      image1: `${baseUrl.conference}/partners/media/media-1.webp`,
      image2: `${baseUrl.conference}/partners/media/media-2.webp`,
      image3: `${baseUrl.conference}/partners/media/media-3.webp`,
      image4: `${baseUrl.conference}/partners/media/media-4.webp`,
      image5: `${baseUrl.conference}/partners/media/media-5.webp`,
      image6: `${baseUrl.conference}/partners/media/media-6.png`,
      image7: `${baseUrl.conference}/partners/media/media-7.png`,
      image8: `${baseUrl.conference}/partners/media/media-8.jpg`,
      image9: `${baseUrl.conference}/partners/media/media-9.png`,
      image10: `${baseUrl.conference}/partners/media/media-10.webp`,
      image11: `${baseUrl.conference}/partners/media/media-11.webp`,
      image12: `${baseUrl.conference}/partners/media/media-12.webp`,
      image13: `${baseUrl.conference}/partners/media/media-13.webp`,
      image14: `${baseUrl.conference}/partners/media/media-14.webp`,
    },
  },

  people: {
    michaelZimba: `${baseUrl.conference}/people/speaker-1.webp`,
    michaelMichie: `${baseUrl.conference}/people/speaker-2.webp`,
    joelOnditi: `${baseUrl.conference}/people/speaker-3.webp`,
    benaiahWepundi: `${baseUrl.conference}/people/speaker-4.webp`,
    solomonWanjiru: `${baseUrl.conference}/people/speaker-5.webp`,
    violetOchieng: `${baseUrl.conference}/people/speaker-6.webp`,
    lyelaMutisya: `${baseUrl.conference}/people/speaker-7.webp`,
    nathanRoss: `${baseUrl.conference}/people/speaker-8.webp`,
    mwangiKirubi: `${baseUrl.conference}/people/speaker-9.webp`,
    sahilPatel: `${baseUrl.conference}/people/speaker-10.webp`,
    robinsonMuiru: `${baseUrl.conference}/people/speaker-11.webp`,
    brightGameli: `${baseUrl.conference}/people/speaker-12.webp`,
    koyundiBryan: `${baseUrl.conference}/people/speaker-13.webp`,
    tawandaChihambakwe: `${baseUrl.conference}/people/speaker-14.webp`,
    tolgaOrs: `${baseUrl.conference}/people/speaker-15.webp`,
    robertBlair: `${baseUrl.conference}/people/speaker-16.webp`,
    denisMutua: `${baseUrl.conference}/people/speaker-17.webp`,
    pamelaAdede: `${baseUrl.conference}/people/speaker-18.webp`,
    washingtonOgol: `${baseUrl.conference}/people/speaker-19.webp`,
    antonyNgatia: `${baseUrl.conference}/people/speaker-20.webp`,
    craigCleave: `${baseUrl.conference}/people/speaker-21.webp`,
    joanMbesya: `${baseUrl.conference}/people/speaker-22.webp`,
    bethanyJepchumba: `${baseUrl.conference}/people/speaker-23.webp`,
    dennisMwighusa: `${baseUrl.conference}/people/speaker-24.webp`,
    winnieNjeri: `${baseUrl.conference}/people/speaker-25.jpeg`,
    ezekielOnyango: `${baseUrl.conference}/people/speaker-26.webp`,
    brianGeorge: `${baseUrl.conference}/people/speaker-27.webp`,
    mercyMakau: `${baseUrl.conference}/people/speaker-28.webp`,
    jasonMasai: `${baseUrl.conference}/people/speaker-29.webp`,
    sandeepMain: `${baseUrl.conference}/people/speaker-30.webp`,
    eddieNdichu: `${baseUrl.conference}/people/speaker-31.webp`,
    douglasOkwemba: `${baseUrl.conference}/people/speaker-32.webp`,
    toshGitonga: `${baseUrl.conference}/people/speaker-33.webp`,
    priscahKinyanjui: `${baseUrl.conference}/people/speaker-34.webp`,
    brianOmwenga: `${baseUrl.conference}/people/speaker-35.webp`,
    chepkemoiMagdaline: `${baseUrl.conference}/people/speaker-36.webp`,
    emmanAtwa: `${baseUrl.conference}/people/speaker-37.webp`,
    mercyMau: `${baseUrl.conference}/people/speaker-38.webp`,
    hawkinsMusili: `${baseUrl.conference}/people/speaker-39.webp`,
    deanGichukie: `${baseUrl.conference}/people/speaker-40.webp`,
    martinMirero: `${baseUrl.conference}/people/speaker-41.webp`,
    ednaKarijo: `${baseUrl.conference}/people/speaker-42.webp`,
    charlesMurito: `${baseUrl.conference}/people/speaker-43.webp`,
    kamauMaina: `${baseUrl.conference}/people/speaker-44.webp`,
    sharonHoli: `${baseUrl.conference}/people/speaker-45.webp`,
    georgeMatuthu: `${baseUrl.conference}/people/speaker-46.webp`,
    loiseMwangi: `${baseUrl.conference}/people/speaker-47.webp`,
    alfredOngere: `${baseUrl.conference}/people/speaker-48.webp`,
    hillaryWangila: `${baseUrl.conference}/people/speaker-49.webp`,
    francisOmondi: `${baseUrl.conference}/people/speaker-50.webp`,
    mosesKimebaro: `${baseUrl.conference}/people/speaker-51.webp`,
    georgeOgada: `${baseUrl.conference}/people/speaker-52.webp`,
    labanCliff: `${baseUrl.conference}/people/speaker-53.webp`,
  },

  posters: {
    speakers: {
      joanMbesya: `${baseUrl.conference}/posters/speakers/poster-1.webp`,
      washingtonOgol: `${baseUrl.conference}/posters/speakers/poster-2.webp`,
      tawandaChihambakwe: `${baseUrl.conference}/posters/speakers/poster-3.webp`,
      eddieNdichu: `${baseUrl.conference}/posters/speakers/poster-4.webp`,
    },

    poster1: `${baseUrl.conference}/posters/poster-1.webp`,
    poster2: `${baseUrl.conference}/posters/poster-2.webp`,
    poster3: `${baseUrl.conference}/posters/poster-3.webp`,
    poster4: `${baseUrl.conference}/posters/poster-4.jpeg`,
  },
};
