import {
  IconBadgeTm,
  IconBrandAirtable,
  IconBuildingFactory,
  IconBulb,
  IconCpu,
  IconDatabase,
  IconDatabaseSearch,
  IconDrone,
  IconFileTextAi,
  IconHeartHandshake,
  IconInfoCircle,
  IconInputAi,
  IconLayersIntersect,
  IconMessageCheck,
  IconMicrophone2,
  IconRocket,
  IconStairsUp,
  IconTrendingUp,
} from '@tabler/icons-react';

export const content = {
  significance: [
    {
      icon: IconInputAi,
      title: 'Artificial Intelligence: Transformative Power',
      desc: 'Artificial Intelligence empowers drones to go beyond simple automation, enabling them to make intelligent decisions based on the data they collect. AI enhances the capabilities of drones enabling them to process and analyze data in real-time, recognize patterns, navigate autonomously and optimize their missions for various applications which makes drones more efficient and adaptable capable of performing a wide range of tasks across different industries.',
    },
    {
      icon: IconDrone,
      title: 'Drones: Unmanned Aerial Systems',
      desc: 'Drones have evolved from Military applications to become versatile tools in civilian domains. They are increasingly used for surveillance, delivery services, agriculture, Inspection, Surveying and mapping etc. Drones play a crucial role in data collection across various fields, providing a cost-effective, efficient, and safe alternative to traditional methods. The continued development of drone technology is likely to expand their applications in the future.',
    },
    {
      icon: IconDatabase,
      title: 'Data: The Fuel for AI',
      desc: 'Data is the lifeblood of artificial intelligence. The abundance of data generated by drones provides a valuable resource for training and enhancing AI algorithms. The data collected by drones include imagery, sensor data, lidar data, weather data, thermal imaging etc. The quality of data collected by drones is crucial, especially in the context of AI applications because it directly impacts the effectiveness and reliability of AI applications. Rigorous data collection processes, validation, and quality assurance are essential to ensure that AI models are well-informed and capable of delivering meaningful insights or performing tasks accurately in various domains.',
    },
    {
      icon: IconLayersIntersect,
      title: 'Synergies and Enhancing Capabilities',
      desc: 'The integration of AI, Drones and Data creates synergies that amplify the capabilities of each component where this convergence is driving innovation such as precision agriculture, disaster response and infrastructure inspection. As we navigate the opportunities presented by this synergy, it is essential to strike a balance between innovation and responsible use, fostering a future where these technologies benefit society at large.',
    },
  ],

  objectives: [
    {
      icon: IconHeartHandshake,
      title: 'Collaborate',
      desc: 'Foster collaboration and networking among professionals in AI, Drone Tech, and Data Analytics.',
    },
    {
      icon: IconBrandAirtable,
      title: 'Exhibit',
      desc: 'Showcase the latest advancements and applications in AI, Drone Technology, and Data Analytics.',
    },
    {
      icon: IconStairsUp,
      title: 'Startup Support',
      desc: 'Provide a platform for startups to showcase their innovative solutions.',
    },
    {
      icon: IconMicrophone2,
      title: 'Talks',
      desc: 'Facilitate knowledge exchange through keynotes, panel discussions, and interactive workshops.',
    },
    {
      icon: IconBulb,
      title: 'Enlighten',
      desc: 'Inspire and motivate attendees to explore the intersections of AI, Drone Tech, and Data for future innovations.',
    },
  ],

  whoAttends: [
    {
      icon: IconCpu,
      title: 'Technology Enthusiasts and Professionals',
      desc: 'Individuals passionate about technology and its applications found the conference stimulating and informative.',
    },
    {
      icon: IconBuildingFactory,
      title: 'Industry Leaders and Decision Makers',
      desc: 'The event drew senior executives and decision-makers seeking to understand how to leverage these technologies for competitive advantage.',
    },
    {
      icon: IconFileTextAi,
      title: 'AI Researchers and Developers',
      desc: 'The conference offered a valuable forum for AI experts to share their latest research and connect with potential collaborators.',
    },
    {
      icon: IconDrone,
      title: 'Drone Technology Experts & Enthusiasts',
      desc: 'Drone enthusiasts, pilots, and manufacturers benefited from the insights and demonstrations centered around drone applications.',
    },
    {
      icon: IconTrendingUp,
      title: 'Startups and Entrepreneurs in Tech Space',
      desc: 'The conference provided a launchpad for early-stage tech startups to gain visibility and forge strategic connections.',
    },
    {
      icon: IconDatabaseSearch,
      title: 'Data Scientists and Analysts',
      desc: 'Data professionals discovered new techniques and tools for harnessing the power of data within the context of AI and drone technology.',
    },
  ],

  whyAttend: [
    {
      icon: IconBrandAirtable,
      title: 'Showcasing Products and Services',
      desc: 'Exhibiting will allow you to showcase your AI, Drone Tech, or Data Analytics products and services to a targeted audience. This will help in generating interest and attract potential customers or clients.',
    },
    {
      icon: IconBadgeTm,
      title: 'Market Exposure',
      desc: 'The expo will attract attendees from various industries and sectors providing an opportunity to gain exposure to a diverse audience. This exposure will increase brand visibility and awareness withing your target market.',
    },
    {
      icon: IconInfoCircle,
      title: 'Competitive Insights',
      desc: 'By attending and exhibiting at this Conference & Expo, you will gain insights into what your competitors are doing. This understanding will help you refine your strategies and offerings to stay competitive in the market.',
    },
    {
      icon: IconRocket,
      title: 'Product Launch Opportunities',
      desc: 'If you have a new product or service, this will be the ideal platform for it’s launch. The targeted audience may be more receptive to innovations, and you can generate immediate interest.',
    },
    {
      icon: IconMessageCheck,
      title: 'Feedback & Market Validation',
      desc: 'Interacting with the attendees during this event, wilallow you to gather feedback on your products and services. This feedback can be invaluable for making improvements and validating your market approach.',
    },
  ],
};
